import "../globals.css"
import { Header } from "@/sections/header"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="es-CL">
      <body className="bg-black">{children}</body>
    </html>
  )
}
