import "./globals.css";
import { Header } from '@/sections/header';
import { Footer } from '@/sections/footer';

export const metadata = {
  title: "BotiCharly.cl",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es-CL">
      <body className="bg-black">
        <Header />

        {children}
        
        <Footer />
      </body>
    </html>
  );
}
